project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Gender Difference accross country and time"
  author:
    - ZIRUI WANG(zw2578)
    - MENGXUAN YU (jy3351)
  repo-url: https://github.com/YOUR_GITHUB_ACCOUNT/REPO_NAME
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


