# Conclusion
In this project, we did exploratory data analysis on the problem: "Is there gender difference in employment, health and education data? If there is, how does this difference change in different countries? Besides, how does this difference change through history?" For education, the analysis shows significant progress in gender equality in education across G7 countries, with gender equality in primary enrollment, tertiary enrollment and math skills. However, some countries in Africa and Asia still show significant gender inequality in intake ratio of primary school. As for employment, gender equality is generally established in employment process including unemployment rate and legislation for job recruitment, but gender inequality in payment is still an issue present in U.S. and other countries without legislation protecting equal payment. For health, gender difference exist in the health conditions of male and female, with Respiratory diseases and Cardiovascular diseases cause more death for men and alcohol, diabetes and hypertension have higher prevalence in men. In conclusion, gender difference present in health and payment across different countries over time, and present less in employment process and education. The limitation of this research is that we mainly focus on G7 countries when analyzing the data from different countries. All seven countries come from high income group, which decreases the diversity of the data. One future improvement that can be made to this research is choosing data from a variety of countries, including different income groups, different continents and different cultures, in order to get a more complete version of the story of gender difference. 